echo "# BPC-Exercises" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/calinel2001/BPC-Exercises.git
git push -u origin main
